[book]
authors = ["onqtam"]
language = "en"
multilingual = false
src = "src"
title = "Headjack - the base layer of cyberspace"

[build]
build-dir = "docs"
create-missing = false

[output.html]
git-repository-url = "https://github.com/onqtam/headjack"
git-repository-icon = "fa-github"
default-theme = "ayu"
preferred-dark-theme = "ayu"

[output.html.fold]
enable = true
level = 0
