/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // mainSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  mainSidebar: [
    // 'what/index',

    // - [What is Headjack](introduction.md)

    {
      type: 'category',
      label: 'What is Headjack',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'what/index',
      },
      items: [
        'what/principles',
        'what/identity',
        {
          type: 'category',
          label: 'Addressing',
          link: {
            type: 'doc',
            id: 'what/addressing',
          },
          items: [
            'what/host_vs_data_centric',
            'what/blobs_and_uris',
            'what/names_and_paths',
          ],
        },
        'what/messages',
        'what/idms_preferences',
        'what/store_and_retrieve',
        'what/blocks_state_proofs',
        'what/numbers',
        'what/competition',
      ],
    },
    {
      type: 'category',
      label: 'Why Headjack',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'why/index',
      },
      items: [
        'why/trololo',
      ],
    },
  ],

};

module.exports = sidebars;
