/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',

    {
      type: 'category',
      label: 'What is Headjack',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'what/index',
      },
      items: [
        'what/trololo',
      ],
    },
    {
      type: 'category',
      label: 'Why Headjack',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'why/index',
      },
      items: [
        'why/trololo',
      ],
    },

    // {
    //   // id: 'IDM',
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['stuff'],
    // },
  ],

};

module.exports = sidebars;
